{
  "openapi" : "3.0.0",
  "servers" : [ {
    "description" : "Comprando.io API V1",
    "url" : "http://api.comprando.io/v1/"
  }, {
    "description" : "SwaggerHub API Auto Mocking",
    "url" : "https://virtserver.swaggerhub.com/Comprando3/Comprando/1.0.0"
  } ],
  "info" : {
    "version" : "1.0.0",
    "title" : "Comprando API V1",
    "description" : "This is the first version of the API used for the  **mobile clients** (*iOS and Andriod*). It will focus on the buyer's operations.  Visit [http://comprando.io/](http://comprando.io/). Jira [http://jira.comprando.io/](http://jira.comprando.io/), Documentation and Wiki [http://docs.comprando.io](http://docs.comprando.io), API Documentation [http://apidocs.comprando.io/](http://apidocs.comprando.io/) and the Stagging server [http://stagging.comprando.io/](http://stagging.comprando.io/)."
  },
  "paths" : {
    "/authenticate" : {
      "post" : {
        "summary" : "Authenticate user and get JWT",
        "description" : "This is the entry point for the API you have to get the JSON Web Token to access the rest of API resources.\n",
        "security" : [ ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "object",
                  "properties" : {
                    "auth_token" : {
                      "type" : "string"
                    },
                    "user" : {
                      "type" : "object",
                      "properties" : {
                        "id" : {
                          "type" : "integer"
                        },
                        "email" : {
                          "type" : "string"
                        },
                        "full_name" : {
                          "type" : "string"
                        },
                        "mobile" : {
                          "type" : "string"
                        },
                        "avatar" : {
                          "type" : "object",
                          "properties" : {
                            "url" : {
                              "type" : "string"
                            }
                          }
                        }
                      }
                    }
                  },
                  "example" : {
                    "auth_token" : "eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxfQ.Hl3PblT_RcxmeMKCr-CTGdsgK_Yqh3RRp6nrA0YZueA",
                    "user" : {
                      "id" : 1,
                      "email" : "islam.askar@gmail.com",
                      "full_name" : "Islam Askar",
                      "mobile" : "01111100956",
                      "avatar" : {
                        "url" : "/uploads/user/avatar/6/avatar.jpeg"
                      }
                    }
                  }
                }
              }
            }
          },
          "401" : {
            "description" : "Unauthorized",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "object",
                  "properties" : {
                    "erros" : {
                      "type" : "array"
                    }
                  },
                  "example" : {
                    "errors" : [ "Invalid Email/Mobile or Password" ]
                  }
                }
              }
            }
          }
        },
        "requestBody" : {
          "description" : "You have to provide some paramters to authenticate, send Email or Mobile and password",
          "required" : true,
          "content" : {
            "application/json" : {
              "schema" : {
                "type" : "object",
                "properties" : {
                  "email" : {
                    "type" : "string"
                  },
                  "password" : {
                    "type" : "string"
                  }
                },
                "required" : [ "email", "password" ],
                "example" : {
                  "email" : "islam.askar@gmail.com",
                  "password" : "123456"
                }
              }
            }
          }
        }
      }
    },
    "/register" : {
      "post" : {
        "summary" : "Register user to the system",
        "description" : "Add a user to the system\n",
        "security" : [ ],
        "responses" : {
          "201" : {
            "description" : "Entity Created",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "object",
                  "properties" : {
                    "auth_token" : {
                      "type" : "string"
                    },
                    "user" : {
                      "type" : "object",
                      "properties" : {
                        "id" : {
                          "type" : "integer"
                        },
                        "email" : {
                          "type" : "string"
                        },
                        "full_name" : {
                          "type" : "string"
                        }
                      }
                    }
                  },
                  "example" : {
                    "auth_token" : "eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxfQ.Hl3PblT_RcxmeMKCr-CTGdsgK_Yqh3RRp6nrA0YZueA",
                    "user" : {
                      "id" : 1,
                      "email" : "islam.askar@gmail.com",
                      "full_name" : "Islam Askar",
                      "mobile" : "01111100956",
                      "avatar" : {
                        "url" : "/uploads/user/avatar/6/avatar.jpeg"
                      }
                    }
                  }
                }
              }
            }
          },
          "422" : {
            "description" : "Unprocessable Entity",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "object",
                  "properties" : {
                    "erros" : {
                      "type" : "array"
                    }
                  },
                  "example" : {
                    "email" : [ "has already been taken" ]
                  }
                }
              }
            }
          }
        },
        "requestBody" : {
          "description" : "To register send the following Full name, Email, Mobile, Password and Avatar as base64 string",
          "required" : true,
          "content" : {
            "application/json" : {
              "schema" : {
                "type" : "object",
                "properties" : {
                  "user" : {
                    "type" : "object",
                    "properties" : {
                      "full_name" : {
                        "type" : "string"
                      },
                      "mobile" : {
                        "type" : "string"
                      },
                      "email" : {
                        "type" : "string"
                      },
                      "password" : {
                        "type" : "string"
                      },
                      "avatar" : {
                        "type" : "string",
                        "format" : "byte"
                      },
                      "provider" : {
                        "type" : "string",
                        "enum" : [ "google_oauth2", "facebook_oauth2" ]
                      },
                      "uid" : {
                        "type" : "string",
                        "description" : "Facebook Client ID / Google ID"
                      }
                    },
                    "required" : [ "email", "password", "mobile" ]
                  }
                },
                "example" : {
                  "user" : {
                    "full_name" : "Islam Askar",
                    "mobile" : "01111100956",
                    "email" : "islam.askar@gmail.com",
                    "password" : "123456",
                    "avatar" : "data:image/jpeg;base64,/9j/4AAQ....",
                    "provider" : "google_oauth2",
                    "uid" : "1488792969"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/categories" : {
      "get" : {
        "summary" : "List shops categories",
        "description" : "Return all the shop categories",
        "security" : [ ],
        "responses" : {
          "200" : {
            "description" : "Successfully returned a list of shops categories",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "object",
                  "properties" : {
                    "categories" : {
                      "type" : "array",
                      "items" : {
                        "type" : "object",
                        "properties" : {
                          "id" : {
                            "type" : "integer"
                          },
                          "name" : {
                            "type" : "string"
                          },
                          "description" : {
                            "type" : "string"
                          },
                          "image" : {
                            "type" : "object",
                            "properties" : {
                              "url" : {
                                "type" : "string"
                              }
                            }
                          }
                        }
                      }
                    }
                  },
                  "example" : {
                    "categories" : [ {
                      "id" : 1,
                      "name" : "Bakery",
                      "description" : "Test Desc",
                      "image" : {
                        "url" : "/uploads/category/image/1/image1.jpg"
                      }
                    }, {
                      "id" : 3,
                      "name" : "Clothes",
                      "description" : "Test Desc",
                      "image" : {
                        "url" : "/uploads/category/image/3/image3.jpg"
                      }
                    } ]
                  }
                }
              }
            }
          }
        }
      }
    },
    "/shops" : {
      "get" : {
        "summary" : "List nearby/offshore shops based on parameters",
        "description" : "List nearby/offshore shops based on parameters",
        "security" : [ ],
        "parameters" : [ {
          "in" : "query",
          "name" : "shop_type",
          "schema" : {
            "type" : "string"
          },
          "description" : "Determine the type of the desired shops ( nearby / offshore )"
        }, {
          "name" : "country_id",
          "in" : "query",
          "schema" : {
            "type" : "integer"
          },
          "description" : "Specifies the id of the country to search in"
        }, {
          "name" : "city_id",
          "in" : "query",
          "schema" : {
            "type" : "integer"
          },
          "description" : "Specifies the id of the city to search in"
        }, {
          "name" : "region_id",
          "in" : "query",
          "schema" : {
            "type" : "integer"
          },
          "description" : "Specifies the id of the region to search in"
        } ],
        "responses" : {
          "200" : {
            "description" : "Successfully returned a list of shops"
          }
        }
      }
    },
    "/shops/{shop_id}/products" : {
      "get" : {
        "summary" : "List shop products",
        "description" : "List shop products with their categories",
        "security" : [ ],
        "parameters" : [ {
          "in" : "path",
          "name" : "shop_id",
          "schema" : {
            "type" : "integer"
          },
          "required" : true,
          "description" : "The shop id which the products belong to"
        } ],
        "responses" : {
          "200" : {
            "description" : "Successfully returned a list of shop products",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "object",
                  "properties" : {
                    "categories" : {
                      "type" : "array",
                      "items" : {
                        "type" : "object",
                        "properties" : {
                          "name" : {
                            "type" : "string"
                          },
                          "products" : {
                            "type" : "array",
                            "items" : {
                              "type" : "object",
                              "properties" : {
                                "id" : {
                                  "type" : "integer"
                                },
                                "name" : {
                                  "type" : "string"
                                },
                                "description" : {
                                  "type" : "string"
                                },
                                "price" : {
                                  "type" : "number",
                                  "format" : "float"
                                },
                                "images" : {
                                  "type" : "array",
                                  "items" : {
                                    "type" : "object",
                                    "properties" : {
                                      "url" : {
                                        "type" : "string"
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  },
                  "example" : {
                    "categories" : [ {
                      "name" : "Dessert",
                      "products" : [ {
                        "id" : 10,
                        "name" : "Macaroons",
                        "description" : "Box of 7 Macaroons",
                        "price" : 56,
                        "images" : [ {
                          "url" : "/uploads/product/images/10/1.png"
                        }, {
                          "url" : "/uploads/product/images/10/2.png"
                        } ]
                      }, {
                        "id" : 1,
                        "name" : "new",
                        "description" : "test",
                        "price" : 18,
                        "images" : [ {
                          "url" : "/uploads/product/images/1/3.png"
                        } ]
                      } ]
                    } ]
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "User" : {
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "integer"
          },
          "email" : {
            "type" : "string"
          },
          "full_name" : {
            "type" : "string"
          },
          "avatar" : {
            "type" : "object",
            "properties" : {
              "url" : {
                "type" : "string"
              }
            }
          }
        }
      }
    },
    "securitySchemes" : {
      "bearerAuth" : {
        "type" : "http",
        "scheme" : "bearer",
        "bearerFormat" : "JWT"
      }
    }
  },
  "security" : [ {
    "bearerAuth" : [ ]
  }, {
    "accessCode" : [ "read", "write" ]
  } ]
}